### ISSUE TITLE
Increasing iOS 8 payload size to 2KB

### ISSUE THREAD

**Issue by pwightman** [arthurnn/apn_sender#79]
[The current payload size](https://github.com/arthurnn/apn_sender/blob/master/lib/apn/notification.rb#L24) is set as a hard 255 byte limit, but iOS 8 has increased the payload size to 2KB. From [Apple's documentation](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html), it would appear it applies only to iOS 8, however. Relevant section:

![docs](http://d.pr/i/tDPH/4jcJdbvU.png)

We adjusted the limit [in a fork](https://github.com/atomkirk/apn_sender/commit/9fb3a2b75c611f403985f7a43f7f70710c90eb58) but is just changing the limit globally desirable? Any preferences on a way to let them specify?

**Comment by benjaminharel** [comment]
I have the same issue.... Any solutions?
Except of it works like a charm.

**Comment by arthurnn** [comment]
Feel free to open a PR to fix the problem.
thanks

**Comment by lukeasrodgers** [comment]
I believe this was effectively addressed by #85
