### ISSUE TITLE
Enhanced Notification Format not supported (incl 2048 byte limit)

### ISSUE THREAD

**Issue by serioushaircut** [arthurnn/apn_sender#90]
Hi there,

Apple introduced a new *byte format* of messages that supports up to 2048 byte limit for messages etc. and a lot more. Be careful, the byte format of these new messages is different. So just sending more bytes via old commands does not work, regardless whether the apn sender limitation within this code has been increased.

Compare this here Figure 5-1 from here (the new one - command level 2):
https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html#//apple_ref/doc/uid/TP40008194-CH101-SW4

to here Figure A -1 (very old - command level 0):
https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/LegacyFormat.html#//apple_ref/doc/uid/TP40008194-CH105-SW2

and here Figure A - 2 (newer - command level 1)
https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/LegacyFormat.html#//apple_ref/doc/uid/TP40008194-CH105-SW5

The last two are (now) flagged as legacy and anything send via this format gets treated accordingly (incl limitations)
Only the newest one supports the larger messages and these other stuff.

Let's see whether we find the time to open a pull request :)
Cheers
SH

**Comment by robinbrandt** [comment]
I'm working on it.

**Comment by arthurnn** [comment]
Thanks for the PR @robinbrandt 
@serioushaircut Do you wanna test it out now?

thanks all

**Comment by serioushaircut** [comment]
done, great.
